

class Card:
    def __init__(self):
        self.id = ""
        self.name = ""
        self.attribute = ""
        self.link = ""
        self.link_arrows = ""
        self.rank = ""
        self.level = ""
        self.attack = ""
        self.defense = ""
        self.type = ""
        self.pend_scale = ""
        self.pend_effect = ""
        self.spell_attribute = ""
        self.summoning_condition = ""
        self.card_text = ""
        self.card_supports = ""
        self.card_anti_supports = ""
        self.card_actions = ""
        self.card_passcode = ""
        self.effect_types = ""
        self.card_status = ""
        self.race = ""
        self.archetype = ""
        self.other_languages = {}


    def clear(self):
        self.id = ""
        self.name = ""
        self.attribute = ""
        self.link = ""
        self.link_arrows = ""
        self.rank = ""
        self.level = ""
        self.attack = ""
        self.defense = ""
        self.type = ""
        self.pend_scale = ""
        self.pend_effect = ""
        self.spell_attribute = ""
        self.summoning_condition = ""
        self.card_text = ""
        self.card_supports = ""
        self.card_anti_supports = ""
        self.card_actions = ""
        self.card_passcode = ""
        self.effect_types = ""
        self.card_status = ""
        self.race = ""
        self.archetype = ""